#!/usr/bin/env bash
# =============================================================================
# Apply the SpectraBreast-Unified migration on top of SpectraBreast-Vision.
#
# Run this from the root of the Vision repo, ON A NEW BRANCH:
#
#   git switch -c merge/spectrabreast-unified
#   bash apply_unified_migration.sh /path/to/SpectraBreast-Registration \
#                                   /path/to/this/spectrabreast-unified/staging
# =============================================================================
set -euo pipefail

if [ $# -ne 2 ]; then
    echo "Usage: $0 <path-to-Registration-repo> <path-to-unified-staging>"
    echo ""
    echo "  <path-to-Registration-repo>  : your local clone of SpectraBreast-Registration"
    echo "  <path-to-unified-staging>    : the staging directory generated by Claude"
    echo "                                 (contains the new spectra/, configs/, pyproject.toml, etc.)"
    exit 1
fi

REG_REPO="$1"
STAGING="$2"

echo ">>> Verifying staging area..."
test -d "$STAGING/spectra/registration" || { echo "ERROR: staging missing spectra/registration"; exit 1; }
test -f "$STAGING/spectra/cli.py"        || { echo "ERROR: staging missing spectra/cli.py"; exit 1; }

echo ">>> Step 1/5: Move existing spectra/* into spectra/vision/* (preserves git history)."
mkdir -p spectra/vision
git mv spectra/__init__.py     spectra/vision/__init__.py
git mv spectra/__main__.py     spectra/vision/__main__.py 2>/dev/null || true   # will be replaced
git mv spectra/cli.py          spectra/vision/_legacy_cli.py 2>/dev/null || true
git mv spectra/config.py       spectra/vision/config.py
git mv spectra/pipeline.py     spectra/vision/pipeline.py
git mv spectra/align.py        spectra/vision/align.py
git mv spectra/aruco.py        spectra/vision/aruco.py
git mv spectra/calibration.py  spectra/vision/calibration.py
git mv spectra/coordinates.py  spectra/vision/coordinates.py
git mv spectra/inputs.py       spectra/vision/inputs.py
git mv spectra/io_utils.py     spectra/vision/io_utils.py
git mv spectra/marker_ba.py    spectra/vision/marker_ba.py
git mv spectra/rerun_logging.py spectra/vision/rerun_logging.py
git mv spectra/surface.py      spectra/vision/surface.py
git mv spectra/transforms.py   spectra/vision/transforms.py
git mv spectra/tui.py          spectra/vision/tui.py 2>/dev/null || true
git mv spectra/viewer.py       spectra/vision/viewer.py
git mv spectra/backends        spectra/vision/backends

echo ">>> Step 2/5: Copy Registration source files into spectra/registration/."
mkdir -p spectra/registration
cp "$REG_REPO/spectrabreast/pipeline.py"     spectra/registration/pipeline.py
cp "$REG_REPO/spectrabreast/pipeline_roi.py" spectra/registration/pipeline_roi.py
cp "$REG_REPO/spectrabreast/roi_align.py"    spectra/registration/roi_align.py
cp "$REG_REPO/spectrabreast/render_gpu.py"   spectra/registration/render_gpu.py

# Rewrite the only cross-file import in render_gpu.py:
#   from spectrabreast.pipeline import render_orthographic_topview
#   ->
#   from .pipeline import render_orthographic_topview
sed -i 's|from spectrabreast\.pipeline import|from .pipeline import|g'      spectra/registration/render_gpu.py
sed -i 's|from spectrabreast\.pipeline_roi import|from .pipeline_roi import|g' spectra/registration/render_gpu.py
sed -i 's|from spectrabreast\.roi_align import|from .roi_align import|g'    spectra/registration/render_gpu.py
sed -i 's|from spectrabreast import|from . import|g'                         spectra/registration/render_gpu.py

# pipeline_roi.py imports from `.pipeline` and `.roi_align` already (relative imports
# inside the legacy spectrabreast package), so it's a no-op — but rewrite anyway
# for safety in case future commits add absolute imports.
for f in spectra/registration/*.py; do
    sed -i 's|from spectrabreast\.|from .|g' "$f"
    sed -i 's|import spectrabreast\.|import spectra.registration.|g' "$f"
done

git add spectra/registration/

echo ">>> Step 3/5: Drop in the new files (config, cli, orchestrator, registration glue, top-level)."
# These files are NEW — copy them verbatim from staging.
cp "$STAGING/spectra/__init__.py"                 spectra/__init__.py
cp "$STAGING/spectra/__main__.py"                 spectra/__main__.py
cp "$STAGING/spectra/cli.py"                      spectra/cli.py
cp "$STAGING/spectra/config.py"                   spectra/config.py
cp "$STAGING/spectra/orchestrator.py"             spectra/orchestrator.py
cp "$STAGING/spectra/registration/__init__.py"    spectra/registration/__init__.py
cp "$STAGING/spectra/registration/runner.py"      spectra/registration/runner.py
cp "$STAGING/spectra/registration/batch.py"       spectra/registration/batch.py
cp "$STAGING/spectra/registration/sweep.py"       spectra/registration/sweep.py
cp "$STAGING/pyproject.toml"                      pyproject.toml
mkdir -p configs
cp "$STAGING/configs/default.yaml"                configs/default.yaml
mkdir -p docs
cp "$STAGING/docs/MIGRATION_NOTES.md"             docs/MIGRATION_NOTES.md

git add spectra/__init__.py spectra/__main__.py spectra/cli.py \
        spectra/config.py spectra/orchestrator.py \
        spectra/registration/__init__.py spectra/registration/runner.py \
        spectra/registration/batch.py spectra/registration/sweep.py \
        pyproject.toml configs/default.yaml docs/MIGRATION_NOTES.md

echo ">>> Step 4/5: Smoke test imports."
uv sync --no-progress
uv run python -c "
import spectra
from spectra import (
    UnifiedConfig, load_unified_config,
    run_full, run_vision_stage, run_registration_stage,
    run_reconstruction,                      # vision legacy alias
    run_full_pipeline, run_full_pipeline_roi # registration
)
print('OK — all top-level imports resolve.')
print('Version:', spectra.__version__)
"

echo ">>> Step 5/5: CLI smoke test."
uv run spectra --help
uv run spectra vision --help
uv run spectra registration --help
uv run spectra full --help

echo ""
echo "==============================================================================="
echo "  MIGRATION APPLIED."
echo "==============================================================================="
echo "Review with:  git status  /  git diff --stat"
echo "Then commit:  git commit -m 'Merge SpectraBreast-Registration into spectra/'"
